// !!!! THIS FILE IS AUTO-GENERATED - DO NOT MODIFY !!!!
void CopyRect_Cpu(__a0 void * src,__d2 long src_skip,__a1 void * dst,__d3 long dst_skip,__d4 word width_words,__d1 word height);
void Minimap_DrawLine(__d0 short x1,__d1 short y1,__d2 short x2,__d3 short y2,__d5 void * ptr);
void Minimap_DrawLineClip(__d4 short px1,__d5 short py1,__d0 short px2,__d1 short py2,__a2 word * screen);
void Cop_StartBit0(void);
void Cop_StartBit1(__d0 void * bit0);
void Cop_StartBit2(__d0 void * bit0,__d1 void * bit1);
void Cop_StartBit3(__d0 void * bit0,__d1 void * bit1,__d2 void * bit2);
void Cop_StartBit4(__d0 void * bit0,__d1 void * bit1,__d2 void * bit2,__d3 void * bit3);
void Cop_StartBit5(__d0 void * bit0,__d1 void * bit1,__d2 void * bit2,__d3 void * bit3,__d4 void * bit4);
void Cop_SetBit0(void);
void Cop_SetBit1(__d0 void * bit0);
void Cop_SetBit4(__d0 void * bit0,__d1 void * bit1,__d2 void * bit2,__d3 void * bit3);
void Cop_NoSprites(void);
void Cop_TickSprite(void);
void Cop_BitMod(__d0 word mod1,__d1 word mod2);
void Cop_ColorMap(__a1 word * colormap);
void Cop_Palette(__a1 word * palette,__d0 word count);
void Cop_Palette_NZ(__a1 word * palette,__d0 word count);
void Cop_Palette_Fade(__a1 word * colormap,__d0 word count,__d7 word fade);
void ColorMap_Fade(__d0 word count,__a1 word * colormap,__d7 word fade);
void Cop_Rainbow2(__d2 word reg1,__a1 word * grad1,__d3 word reg2,__a2 word * grad2,__d1 word len);
void Cop_Rainbow4(__d1 word reg1,__a1 word * grad1,__d2 word reg2,__a2 word * grad2,__d3 word reg3,__a3 word * grad3,__d4 word reg4,__a4 word * grad4,__d5 word len);
void Cop_Rainbow4x(__d1 word reg1,__a1 word * grad1,__d2 word reg2,__a2 word * grad2,__d3 word reg3,__a3 word * grad3,__d4 word reg4,__a4 word * grad4,__a5 word * grad5,__d5 word len);
void Cop_RainbowWildcat_Init(__a1 word * offmap,__d7 word * copbase,__d5 word len);
void Cop_Wait(void);
void Cop_Wait256(void);
void Cop_End(void);
void Cop_SplitList(__a0 void * copper,__a1 void * splitlist,__a4 void * frame_streams,__a5 void * pal_streams,__a6 void * pal_data,__a3 void * sprites);
void Cop_Gradient(__a1 word * grad);
